[package]
name = "s2n-tls-metrics-subscriber-ffi"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
s2n-tls-metrics-subscriber = { path = "../s2n-tls-metrics-subscriber" }
s2n-tls = { version = "0.3", path = "../../extended/s2n-tls", features = ["unstable-events"] }
s2n-tls-sys = { version = "0.3", path = "../../extended/s2n-tls-sys", features = ["unstable-events"] }
tokio = { version = "1.0", features = ["rt-multi-thread"] }
libc = "0.2"
